apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-config
  labels:
    app: web-app
data:
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "anchor-research.firebaseapp.com"
  NEXT_PUBLIC_PROJECT_ID: "anchor-research"
  NEXT_PUBLIC_SEC_EDGAR_BUCKET: "sec-edgar-anchor-public"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "129721768322"
  NEXT_PUBLIC_FIREBASE_APP_ID: "1:129721768322:web:0282663927d48f3f88d79b"
  NEXT_PUBLIC_STOCK_AGENT_API_URL: "http://stock-analysis-agent:8080"
